### ISSUE TITLE
Transient errors in post-job cache action

### ISSUE THREAD

**Issue by alexarchambault** [coursier/cache-action#131]
https://github.com/scalameta/metals/pull/2608#issuecomment-799228719

```text
Post job cleanup.
coursier cache key:
  coursier-unit-matrix-c72830702e1d2b18a132b9d6e3742571e19e9466-33aa363d8c15033b2a8ed0d8c299d77f17660736
Saving coursier cache
C:\windows\System32\tar.exe --posix -z -cf cache.tgz -P -C D:/a/metals/metals --files-from manifest.txt
Warning:  Cache service responded with 429 during upload chunk.
  
sbt-ivy2-cache cache key:
  sbt-ivy2-cache-unit-matrix-c72830702e1d2b18a132b9d6e3742571e19e9466-57ca911780629f6d13612b672c8a32e66547f7b0
Saving sbt-ivy2-cache cache

D:\a\_actions\coursier\cache-action\v6\dist\node_modules\@actions\cache\lib\internal\cacheHttpClient.js:177
                        autoClose: false
^
Error: Cache upload failed because file read failed with EBADF: bad file descriptor, read
    at ReadStream.<anonymous> (D:\a\_actions\coursier\cache-action\v6\dist\node_modules\@actions\cache\lib\internal\cacheHttpClient.js:177:1)
    at ReadStream.emit (events.js:210:5)
    at internal/fs/streams.js:167:12
    at FSReqCallback.wrapper [as oncomplete] (fs.js:470:5)
```

**Comment by alexarchambault** [comment]
https://github.com/actions/toolkit/issues/658#issuecomment-743802056 runs into EBADF too.

**Comment by alexarchambault** [comment]
Maybe we should just trap some errors in the post-job actions, like in https://github.com/world-federation-of-advertisers/actions/pull/3.

**Comment by ckipp01** [comment]
So I see that indeed you have wrapped it in a `Try`, but it seems that this is still causing failures. For example as the Steward prs came into Metals last night every single one failed due to
```
Post job cleanup.
coursier cache key:
  coursier-unit-matrix-feec2582a08e667f913f4512debe660bb1618cf1-1f972e851b541656923c7806272e4376e86abf8b
coursier cache restored from:
  coursier-unit-matrix-feec2582a08e667f913f4512debe660bb1618cf1-32f1a67f49fb62b4ac0856b42ec5bd2a443da8c2
Saving coursier cache
/usr/local/bin/gtar --posix --use-compress-program zstd -T0 -cf cache.tzst -P -C /Users/runner/work/metals/metals --files-from manifest.txt --delay-directory-restore
Warning:  Cache service responded with 429 during upload chunk.
  
sbt-ivy2-cache cache key:
  sbt-ivy2-cache-unit-matrix-feec2582a08e667f913f4512debe660bb1618cf1-317877130acc17b9d3e84ff5f2cb7fb056859d92
sbt-ivy2-cache cache restored from:
  sbt-ivy2-cache-unit-matrix-feec2582a08e667f913f4512debe660bb1618cf1-1573819f82e9338e377bafed35c5ce223aab59c0
Saving sbt-ivy2-cache cache

/Users/runner/work/_actions/coursier/cache-action/v6.1/dist/node_modules/@actions/cache/lib/internal/cacheHttpClient.js:177
                        autoClose: false
^
Error: Cache upload failed because file read failed with EBADF: bad file descriptor, read
    at ReadStream.<anonymous> (/Users/runner/work/_actions/coursier/cache-action/v6.1/dist/node_modules/@actions/cache/lib/internal/cacheHttpClient.js:177:1)
    at ReadStream.emit (events.js:210:5)
    at internal/fs/streams.js:167:12
```
In a variety of OS's. Any idea how to get around this?

**Comment by alexarchambault** [comment]
It seems this error corresponds to https://github.com/actions/toolkit/issues/612, and https://github.com/actions/cache/pull/596 has [a fix](https://github.com/actions/cache/commit/c64c572235d810460d0d6876e9c705ad5002b353#diff-98a430a38f6b3e5963055942f2e487ab7763beb116c257676560e946de06a244) apparently. We could just do the same here.
